# Generated by Django 2.2.10 on 2020-07-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='location',
            field=models.CharField(choices=[('---', '---'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('section 1', 'Section 1'), ('section 2', 'Section 2'), ('section 3', 'Section 3'), ('section 4', 'Section 4')], default='---', max_length=30),
        ),
    ]
